using System.Text.Json.Serialization;

namespace Morgana.Contracts;

/// <summary>
/// Transport-agnostic envelope for a structured outbound message delivered to the end user
/// through an <c>IChannelService</c>. Carries the full payload an actor needs to publish:
/// text, quick replies, rich card, agent identity, error reason, and rendering metadata
/// (message type, fading duration).
/// </summary>
/// <remarks>
/// <para><strong>Wire contract:</strong></para>
/// <para>This DTO is serialized by the active channel implementation (for SignalR +
/// Cauldron, via the "ReceiveMessage" event). Property names and types intentionally match
/// <c>Cauldron.Messages.SignalRMessage</c> so the wire format stays identical.</para>
/// <para><strong>Contract sync policy:</strong></para>
/// <list type="bullet">
/// <item>Required fields must match exactly between backend and frontend</item>
/// <item>Optional fields can be added without breaking compatibility (use default values)</item>
/// <item>Field removal or type changes are BREAKING and require coordinated deployment</item>
/// </list>
/// </remarks>
public sealed class ChannelMessage
{
    /// <summary>
    /// Unique identifier of the conversation this message belongs to.
    /// Used for channel group routing and conversation correlation.
    /// </summary>
    [JsonPropertyName("conversationId")]
    public required string ConversationId { get; init; }

    /// <summary>
    /// Message text to display to the user.
    /// May contain markdown, emojis, or plain text depending on UI renderer capabilities.
    /// </summary>
    [JsonPropertyName("text")]
    public required string Text { get; init; }

    /// <summary>
    /// UTC timestamp when this message was generated by the backend.
    /// Used for message ordering and display in the UI.
    /// </summary>
    [JsonPropertyName("timestamp")]
    public DateTime Timestamp { get; init; } = DateTime.UtcNow;

    /// <summary>
    /// Type of message for UI rendering and styling.
    /// Valid values: "assistant", "presentation", "system", "system_warning", "error"
    /// Default: "assistant"
    /// </summary>
    [JsonPropertyName("messageType")]
    public string MessageType { get; init; } = "assistant";

    /// <summary>
    /// Optional list of quick reply buttons for user interaction.
    /// When present, UI should render these as clickable buttons.
    /// QuickReplies are generated by the LLM and constitute a stable contract.
    /// Null when no quick replies are available.
    /// </summary>
    [JsonPropertyName("quickReplies")]
    public List<QuickReply>? QuickReplies { get; init; }

    /// <summary>
    /// Optional rich card for structured visual presentation.
    /// When present, renders structured data components instead of plain text formatting.
    /// </summary>
    [JsonPropertyName("richCard")]
    public RichCard? RichCard { get; init; }

    /// <summary>
    /// Optional error reason code when MessageType is "error" or "system_warning".
    /// Examples: "timeout", "rate_limit_exceeded", "guard_violation".
    /// Null for non-error messages.
    /// </summary>
    [JsonPropertyName("errorReason")]
    public string? ErrorReason { get; init; }

    /// <summary>
    /// Name of the agent that generated this message.
    /// Examples: "Morgana", "Morgana (Billing)", "Morgana (Technical Support)".
    /// Default: "Morgana"
    /// </summary>
    [JsonPropertyName("agentName")]
    public string AgentName { get; init; } = "Morgana";

    /// <summary>
    /// Indicates whether this specialized agent has completed its task.
    /// When true, control returns to the base Morgana orchestrator.
    /// Default: false
    /// </summary>
    [JsonPropertyName("agentCompleted")]
    public bool AgentCompleted { get; init; }

    /// <summary>
    /// Duration of the eventual fading message which will be generated
    /// by this channel message (depending on its MessageType).
    /// </summary>
    [JsonPropertyName("fadingMessageDurationSeconds")]
    public int? FadingMessageDurationSeconds { get; set; } = 10;

    /// <summary>
    /// Conversation-level metadata (e.g. remaining dust budget). Characterises the
    /// conversation, not this message. Null when no such metadata is available.
    /// </summary>
    [JsonPropertyName("conversationMetadata")]
    public ConversationMetadata? ConversationMetadata { get; init; }
}
