#!/bin/bash

# ==============================================================================
# SET VERSION ENVIRONMENT VARIABLES
# ==============================================================================
# Extracts versions from Directory.Build.props and creates .env file
# for docker-compose to use.
#
# Usage:
#   source ./set-versions.sh    # Load into current shell
#   ./set-versions.sh           # Just create .env file

set -e

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}📋 Extracting versions from Directory.Build.props...${NC}"

# Extract Morgana version
if [ -f "Morgana/Directory.Build.props" ]; then
    MORGANA_VERSION=$(grep -oP '(?<=<Version>)[^<]+' Morgana/Directory.Build.props | head -1)
    echo -e "${GREEN}   ✓ Morgana:  ${MORGANA_VERSION}${NC}"
else
    echo "Error: Morgana/Directory.Build.props not found!" >&2
    exit 1
fi

# Extract Cauldron version
if [ -f "Cauldron/Directory.Build.props" ]; then
    CAULDRON_VERSION=$(grep -oP '(?<=<Version>)[^<]+' Cauldron/Directory.Build.props | head -1)
    echo -e "${GREEN}   ✓ Cauldron: ${CAULDRON_VERSION}${NC}"
else
    echo "Error: Cauldron/Directory.Build.props not found!" >&2
    exit 1
fi

# Create/update .env.versions file
cat > .env.versions << EOF
# Auto-generated by set-versions.sh from Directory.Build.props
# DO NOT EDIT MANUALLY - this file is regenerated on each build

MORGANA_VERSION=${MORGANA_VERSION}
CAULDRON_VERSION=${CAULDRON_VERSION}
EOF

echo -e "${GREEN}✅ Created .env.versions${NC}"
echo ""
echo "To use these versions with docker-compose:"
echo "  docker compose --env-file .env --env-file .env.versions build"
echo "  docker compose --env-file .env --env-file .env.versions up -d"
echo ""
echo "Or source this script to export to current shell:"
echo "  source ./set-versions.sh"

# Export variables if sourced
export MORGANA_VERSION
export CAULDRON_VERSION
