# ==============================================================================
# SET VERSION ENVIRONMENT VARIABLES (PowerShell)
# ==============================================================================
# Extracts versions from Directory.Build.props and creates .env file
# for docker-compose to use.
#
# Usage:
#   .\set-versions.ps1           # Create .env.versions file
#   . .\set-versions.ps1         # Dot-source to load into current session

# Stop on errors
$ErrorActionPreference = "Stop"

# Colors
function Write-Info($message) {
    Write-Host $message -ForegroundColor Cyan
}

function Write-Success($message) {
    Write-Host $message -ForegroundColor Green
}

function Write-Error($message) {
    Write-Host $message -ForegroundColor Red
}

Write-Info "📋 Extracting versions from Directory.Build.props..."

# Extract Morgana version
$morganaPropsPath = "Morgana\Directory.Build.props"
if (-Not (Test-Path $morganaPropsPath)) {
    Write-Error "Error: $morganaPropsPath not found!"
    exit 1
}

$morganaXml = [xml](Get-Content $morganaPropsPath)
$MORGANA_VERSION = $morganaXml.Project.PropertyGroup.Version
if (-Not $MORGANA_VERSION) {
    Write-Error "Error: Could not extract version from $morganaPropsPath"
    exit 1
}
Write-Success "   ✓ Morgana:  $MORGANA_VERSION"

# Extract Cauldron version
$cauldronPropsPath = "Cauldron\Directory.Build.props"
if (-Not (Test-Path $cauldronPropsPath)) {
    Write-Error "Error: $cauldronPropsPath not found!"
    exit 1
}

$cauldronXml = [xml](Get-Content $cauldronPropsPath)
$CAULDRON_VERSION = $cauldronXml.Project.PropertyGroup.Version
if (-Not $CAULDRON_VERSION) {
    Write-Error "Error: Could not extract version from $cauldronPropsPath"
    exit 1
}
Write-Success "   ✓ Cauldron: $CAULDRON_VERSION"

# Create .env.versions file
$envContent = @"
# Auto-generated by set-versions.ps1 from Directory.Build.props
# DO NOT EDIT MANUALLY - this file is regenerated on each build

MORGANA_VERSION=$MORGANA_VERSION
CAULDRON_VERSION=$CAULDRON_VERSION
"@

$envContent | Out-File -FilePath ".env.versions" -Encoding UTF8 -NoNewline

Write-Success "✅ Created .env.versions"
Write-Host ""
Write-Host "To use these versions with docker-compose:"
Write-Host "  docker compose --env-file .env --env-file .env.versions build"
Write-Host "  docker compose --env-file .env --env-file .env.versions up -d"
Write-Host ""
Write-Host "Or dot-source this script to load into current session:"
Write-Host "  . .\set-versions.ps1"

# Export variables if dot-sourced
$env:MORGANA_VERSION = $MORGANA_VERSION
$env:CAULDRON_VERSION = $CAULDRON_VERSION
