namespace Morgana.AI.Interfaces;

/// <summary>
/// Abstraction over the outbound channel that delivers Morgana's responses to an end user.
/// A channel is the transport + client pair (e.g. SignalR + Cauldron web UI, HTTP webhook,
/// polling REST endpoint, ...) through which messages leave the actor system and reach
/// whoever is consuming them.
/// </summary>
/// <remarks>
/// <para><strong>Purpose:</strong></para>
/// <para>This service decouples the actor system from any specific transport. Actors invoke
/// it to emit messages without knowing whether the underlying channel is SignalR, a webhook,
/// Server-Sent Events, or a plain HTTP long-poll.</para>
///
/// <para><strong>Metadata contract:</strong></para>
/// <para>Each implementation advertises its identity and expressive capabilities via
/// <see cref="Metadata"/>. Producers of outbound messages (presenter, agents, supervisor)
/// are expected to consult its capabilities and degrade gracefully when a feature is not
/// supported (e.g. rendering a rich card as plain text, or coalescing streamed chunks into
/// a single final message).</para>
///
/// <para><strong>Built-In implementation:</strong></para>
/// <para><c>SignalRChannelService</c> (in Morgana.Web) is the reference channel backing the
/// Cauldron web UI and advertises full capabilities (rich cards, quick replies, streaming, markdown).</para>
/// </remarks>
public interface IChannelService
{
    /// <summary>
    /// Identity and expressive capabilities advertised by this channel. Consumers must consult
    /// the capability side of this metadata before emitting features that may not be supported
    /// by every transport.
    /// </summary>
    Records.ChannelMetadata Metadata { get; }

    /// <summary>
    /// Sends a message to the conversation group targeted by
    /// <see cref="Records.ChannelMessage.ConversationId"/>. The message envelope carries the
    /// full payload (text, message type, quick replies, rich card, agent identity, error
    /// reason, fading duration) and is delivered through the channel's native transport.
    /// </summary>
    /// <param name="message">The fully-formed channel message to deliver.</param>
    /// <returns>Task representing the async send operation</returns>
    Task SendMessageAsync(Records.ChannelMessage message);

    /// <summary>
    /// Sends a streaming chunk to a conversation group via the channel for progressive response rendering.
    /// Enables real-time display of agent responses as they are generated by the LLM. Implementations
    /// whose <see cref="Metadata"/> capabilities report <c>SupportsStreaming = false</c> are free to no-op.
    /// </summary>
    /// <param name="conversationId">Unique identifier of the conversation (channel group/routing key)</param>
    /// <param name="chunkText">Partial response text to append to the current message</param>
    /// <returns>Task representing the async send operation</returns>
    Task SendStreamChunkAsync(string conversationId, string chunkText);
}