namespace Morgana.AI.Interfaces;

/// <summary>
/// Service interface for bridging the actor system with SignalR for real-time client communication.
/// Abstracts SignalR hub context interactions and provides structured message delivery to conversation groups.
/// </summary>
/// <remarks>
/// <para><strong>Purpose:</strong></para>
/// <para>This service acts as a bridge between the Akka.NET actor system and SignalR, allowing actors to send
/// messages to clients without direct knowledge of SignalR implementation details.</para>
public interface ISignalRBridgeService
{
    /// <summary>
    /// Sends a simple text message to a conversation group via SignalR.
    /// Basic message delivery without structured metadata or quick replies.
    /// </summary>
    /// <param name="conversationId">Unique identifier of the conversation (SignalR group name)</param>
    /// <param name="text">Message text to send to clients</param>
    /// <param name="errorReason">Optional error reason code for error messages (e.g., "guard_violation", "timeout")</param>
    /// <returns>Task representing the async send operation</returns>
    Task SendMessageToConversationAsync(
        string conversationId,
        string text,
        string? errorReason = null);

    /// <summary>
    /// Sends a structured message with full metadata to a conversation group via SignalR.
    /// Supports message types, quick replies, agent identification, and completion status.
    /// </summary>
    /// <param name="conversationId">Unique identifier of the conversation (SignalR group name)</param>
    /// <param name="text">Message text to send to clients</param>
    /// <param name="messageType">Type of message for client-side rendering ("assistant", "presentation", "system", "error")</param>
    /// <param name="quickReplies">Optional list of quick reply buttons for user interaction</param>
    /// <param name="errorReason">Optional error reason code for error messages (e.g., "llm_error", "supervisor_error")</param>
    /// <param name="agentName">Optional name of the agent that generated the response (e.g., "Morgana", "Morgana (Billing)")</param>
    /// <param name="agentCompleted">Flag indicating if the agent has completed its task (affects UI state, conversation flow)</param>
    /// <param name="originalTimestamp">Timestamp of the message when created in UI</param>
    /// <param name="richCard">Optional rich card for structured visual presentation of complex data</param>
    /// <returns>Task representing the async send operation</returns>
    Task SendStructuredMessageAsync(
        string conversationId,
        string text,
        string messageType,
        List<Records.QuickReply>? quickReplies = null,
        string? errorReason = null,
        string? agentName = null,
        bool agentCompleted = false,
        DateTime? originalTimestamp = null,
        Records.RichCard? richCard = null);

    /// <summary>
    /// Sends a streaming chunk to a conversation group via SignalR for progressive response rendering.
    /// Enables real-time display of agent responses as they are generated by the LLM.
    /// </summary>
    /// <param name="conversationId">Unique identifier of the conversation (SignalR group name)</param>
    /// <param name="chunkText">Partial response text to append to the current message</param>
    /// <returns>Task representing the async send operation</returns>
    Task SendStreamChunkAsync(
        string conversationId,
        string chunkText);
}
