using static Morgana.Framework.Records;

namespace Morgana.SignalR.Messages;


/// <summary>
/// <para>
/// SignalR message contract for "ReceiveMessage" event.
/// This matches Cauldron.Messages.SignalRMessage schema.
/// </para>
/// <para>
/// CONTRACT VERSION: 1.0<br/>
/// SYNC WITH: Cauldron
/// </para>
/// <para>
/// BREAKING CHANGES: Any modification to required fields or removal of fields is a breaking change.
/// SAFE CHANGES: Adding optional fields with default values.
/// </para>
/// <para>
/// ⚠️ IMPORTANT: This DTO is duplicated in Cauldron frontend (Cauldron.Messages.SignalRMessage).
/// When making changes, update both versions and ensure backward compatibility.
/// Test serialization/deserialization compatibility with integration tests.
/// </para>
/// </summary>
/// <remarks>
/// <para><strong>Contract Sync Policy:</strong></para>
/// <list type="bullet">
/// <item>Required fields must match exactly between backend and frontend</item>
/// <item>Optional fields can be added without breaking compatibility (use default values)</item>
/// <item>Field removal or type changes are BREAKING and require coordinated deployment</item>
/// </list>
/// <para><strong>Wire Format (JSON):</strong></para>
/// <code>
/// {
///   "conversationId": "abc123",
///   "text": "Hello! How can I help you today?",
///   "timestamp": "2025-01-23T10:30:00Z",
///   "messageType": "assistant",
///   "quickReplies": [
///     { "id": "billing", "label": "💳 Billing", "value": "Show invoices", "termination": false }
///   ],
///   "errorReason": null,
///   "agentName": "Morgana (Billing)",
///   "agentCompleted": true
/// }
/// </code>
/// </remarks>
public sealed class SignalRMessage
{
    /// <summary>
    /// Unique identifier of the conversation this message belongs to.
    /// Used for SignalR group routing and conversation correlation.
    /// </summary>
    public required string ConversationId { get; init; }

    /// <summary>
    /// Message text to display to the user.
    /// May contain markdown, emojis, or plain text depending on UI renderer capabilities.
    /// </summary>
    public required string Text { get; init; }

    /// <summary>
    /// UTC timestamp when this message was generated by the backend.
    /// Used for message ordering and display in the UI.
    /// </summary>
    public DateTime Timestamp { get; init; }

    /// <summary>
    /// Type of message for UI rendering and styling.
    /// Valid values: "assistant", "presentation", "system", "error"
    /// Default: "assistant"
    /// </summary>
    public string MessageType { get; init; } = "assistant";

    /// <summary>
    /// Optional list of quick reply buttons for user interaction.
    /// When present, UI should render these as clickable buttons.
    /// QuickReplies are generated by the LLM and constitute a stable contract.
    /// Null when no quick replies are available.
    /// </summary>
    public List<QuickReply>? QuickReplies { get; init; }

    /// <summary>
    /// Optional error reason code when MessageType is "error".
    /// Examples: "TIMEOUT", "INVALID_INPUT", "SERVICE_UNAVAILABLE"
    /// Null for non-error messages.
    /// </summary>
    public string? ErrorReason { get; init; }

    /// <summary>
    /// Name of the agent that generated this message.
    /// Examples: "Morgana", "Morgana (Billing)", "Morgana (Technical Support)"
    /// Used for UI theming, avatar selection, and conversation context.
    /// Default: "Morgana"
    /// </summary>
    public string AgentName { get; init; } = "Morgana";

    /// <summary>
    /// Indicates whether this specialized agent has completed its task.
    /// When true, control returns to the base Morgana orchestrator.
    /// UI should return to default state (purple theme, base avatar, etc.)
    /// Default: false
    /// </summary>
    public bool AgentCompleted { get; init; }
}